import { supabase, isSupabaseConfigured, supabaseConfigError } from './src/lib/supabase.js';
import duquePortrait from './assets/characters/duque.png';
import assassinaPortrait from './assets/characters/assassina.png';
import capitaoPortrait from './assets/characters/capitao.png';
import embaixadorPortrait from './assets/characters/embaixador.png';
import condessaPortrait from './assets/characters/condessa.png';
import councilChamberDark from './assets/council-chamber.png';
import councilChamberLight from './assets/council-chamber-light.png';

const ROLES={Duque:'Receba 3 moedas',Assassina:'Elimine por 3 moedas',Capitão:'Roube até 2 moedas',Embaixador:'Troque cartas',Condessa:'Bloqueia assassinato'};
const CLAIMS={Imposto:'Duque',Roubar:'Capitão',Trocar:'Embaixador',Assassinar:'Assassina'};
const PORTRAITS={Duque:duquePortrait,Assassina:assassinaPortrait,'Capitão':capitaoPortrait,Embaixador:embaixadorPortrait,Condessa:condessaPortrait};
const PRIORITY_ASSETS=[councilChamberDark,councilChamberLight,...Object.values(PORTRAITS)];
for(const source of PRIORITY_ASSETS){const image=new Image();image.fetchPriority='high';image.decoding='async';image.src=source}
const NAMES=['Lorenzo','Beatrice','Vittorio','Serafina','Dante'];
const roomPathMatch=location.pathname.match(/^\/sala\/([A-Z2-9]{5})\/?$/i);
const inviteCode=(roomPathMatch?.[1]||new URLSearchParams(location.search).get('room')||'').toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,5);
let state={screen:'lobby',mode:inviteCode.length===5?'join':'bots',joinCode:inviteCode,name:'',players:[],deck:[],turn:0,round:1,log:[],busy:false,winner:null,targetAction:null,challenge:null,block:null,room:null,myId:0,isHost:false,online:false,error:null,shareCopied:false};
let roomChannel=null;
const makePlayerId=()=>crypto.randomUUID();
const makeRoomCode=()=>Array.from({length:5},()=> 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[Math.floor(Math.random()*32)]).join('');
const sendRoom=(event,payload={})=>roomChannel?.send({type:'broadcast',event,payload});
const $=s=>document.querySelector(s); const alive=p=>p.cards.some(c=>!c.lost);
const themeToggle=$('#theme-toggle');
function paintThemeToggle(){const light=document.documentElement.dataset.theme==='light';themeToggle.innerHTML=`<span>${light?'☾':'☀'}</span><small>${light?'Tema escuro':'Tema claro'}</small>`;themeToggle.setAttribute('aria-pressed',String(light));document.querySelector('meta[name="theme-color"]').content=light?'#eee8dc':'#090807'}
themeToggle.onclick=()=>{const next=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=next;localStorage.setItem('la-corte-theme',next);paintThemeToggle()};paintThemeToggle();
function deck(){return Object.keys(ROLES).flatMap(r=>[0,1,2].map(()=>({role:r,lost:false}))).sort(()=>Math.random()-.5)}
function start(roomPlayers=null){state.deck=deck();const seats=roomPlayers||Array.from({length:4},(_,i)=>({id:i,name:i?NAMES[i-1]:state.name}));state.players=seats.map((seat,i)=>({id:seat.id,name:seat.name,bot:roomPlayers?false:i>0,courage:.82+Math.random()*.36,coins:2,cards:[state.deck.pop(),state.deck.pop()]}));state.turn=0;state.round=1;state.log=['A corte está reunida. O jogo começou.'];state.screen='game';state.winner=null;render();syncState()}
function connectRoom(kind){if(!isSupabaseConfigured){state.error=supabaseConfigError||'Multiplayer online ainda não foi configurado. Defina VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY.';render();return}state.error=null;roomChannel?.unsubscribe();state.myId=makePlayerId();state.isHost=kind==='create';const code=kind==='create'?makeRoomCode():state.joinCode;roomChannel=supabase.channel(`la-corte:${code}`,{config:{broadcast:{self:false},presence:{key:state.myId}}}).on('broadcast',{event:'join_request'},({payload})=>{if(!state.isHost||state.room?.code!==code||state.room.players.some(p=>p.id===payload.id)||state.room.players.length>=6)return;state.room={...state.room,players:[...state.room.players,{id:payload.id,name:payload.name,connected:true}]};sendRoom('room',{room:state.room});render()}).on('broadcast',{event:'room'},({payload})=>{state.room=payload.room;state.online=true;state.screen='room';if(state.isHost)history.replaceState(null,'',`/sala/${state.room.code}`);render()}).on('broadcast',{event:'game_started'},({payload})=>{if(state.isHost)start(payload.players);else{state.screen='waiting_game';render()}}).on('broadcast',{event:'game_state'},({payload})=>{if(!state.isHost){Object.assign(state,payload.state,{online:true,myId:state.myId,isHost:false,room:state.room});render()}}).on('broadcast',{event:'action'},({payload})=>{if(state.isHost&&state.players[state.turn]?.id===payload.playerId)act(payload.action,payload.targetId,true)}).subscribe((status)=>{if(status==='CHANNEL_ERROR'||status==='TIMED_OUT'||status==='CLOSED'){state.error='Não foi possível conectar ao Supabase. Confira a Project URL e a chave pública configuradas na Vercel.';state.screen='lobby';render();return}if(status!=='SUBSCRIBED')return;state.online=true;if(state.isHost){state.room={code,hostId:state.myId,status:'lobby',players:[{id:state.myId,name:state.name,connected:true}]};state.screen='room';history.replaceState(null,'',`/sala/${code}`);sendRoom('room',{room:state.room});render()}else{state.screen='room';render();sendRoom('join_request',{id:state.myId,name:state.name});setTimeout(()=>{if(!state.room?.players.some(p=>p.id===state.myId)){state.error='Sala não encontrada ou anfitrião offline.';state.screen='lobby';render()}},6000)}})}
function syncState(){if(state.online&&state.isHost){const snapshot={...state,room:null,error:null};sendRoom('game_state',{state:snapshot})}}
function next(){const living=state.players.filter(alive);if(living.length===1){state.winner=living[0];render();syncState();return}do{state.turn=(state.turn+1)%state.players.length;if(state.turn===0)state.round++}while(!alive(state.players[state.turn]));state.busy=false;render();syncState();if(state.players[state.turn].bot)setTimeout(botTurn,900)}
function lose(p){const card=p.cards.find(c=>!c.lost);if(card)card.lost=true}
function replaceProvenCard(player,proof){player.cards=player.cards.filter(c=>c!==proof);state.deck.push({...proof,lost:false});state.deck.sort(()=>Math.random()-.5);player.cards.push(state.deck.pop())}
function act(type,targetId,remote=false){if(state.busy)return;const current=state.players[state.turn];if(state.online&&!state.isHost&&!remote){sendRoom('action',{playerId:state.myId,action:type,targetId});state.busy=true;render();return}if(state.online&&state.isHost&&!remote&&current.id!==state.myId)return;state.busy=true;const p=current,t=state.players.find(x=>x.id===targetId);let msg=`${p.name} `;
 if(type==='Renda'){p.coins++;msg+='recolheu 1 moeda.'}
 if(type==='Ajuda externa'){p.coins+=2;msg+='recebeu ajuda externa (+2).' }
 if(type==='Imposto'){p.coins+=3;msg+='alegou ser Duque e cobrou 3 moedas.'}
 if(type==='Roubar'){const n=Math.min(2,t.coins);t.coins-=n;p.coins+=n;msg+=`roubou ${n} moeda(s) de ${t.name}.`}
 if(type==='Assassinar'){p.coins-=3;lose(t);msg+=`ordenou o assassinato de ${t.name}.`}
 if(type==='Golpe'){p.coins-=7;lose(t);msg+=`lançou um golpe contra ${t.name}.`}
 if(type==='Trocar'){const active=p.cards.filter(c=>!c.lost);const options=[...active.map(c=>c.role),state.deck.pop().role,state.deck.pop().role].sort(()=>Math.random()-.5);let k=0;p.cards=p.cards.map(c=>c.lost?c:{role:options[k++],lost:false});msg+='reorganizou suas influências.'}
 state.log.push(msg);render();setTimeout(next,700)}
function chooseTarget(type){state.targetAction=type;render()}
const BLOCKS={'Ajuda externa':['Duque'],Roubar:['Capitão','Embaixador'],Assassinar:['Condessa']};
function eligibleBlockers(type,actorId,targetId){const roles=BLOCKS[type];if(!roles)return[];return state.players.filter(p=>{if(!alive(p)||p.id===actorId)return false;if(type==='Ajuda externa')return true;return p.id===targetId})}
function requestAction(type,targetId,fromBot=false){const p=state.players[state.turn],role=CLAIMS[type];if(role&&fromBot&&alive(state.players.find(x=>x.id===state.myId))){state.challenge={type,targetId,actorId:p.id,role};state.busy=true;render();return}if(role&&!fromBot&&!state.online){const challenger=chooseBotChallenger(role,p.id);if(challenger){resolveBotChallenge(challenger,p,role,type,targetId);return}}advanceAction(type,targetId,fromBot)}
function advanceAction(type,targetId,fromBot=false){const actor=state.players[state.turn],roles=BLOCKS[type];if(!roles)return act(type,targetId,fromBot);const me=state.players.find(p=>p.id===state.myId);const humanCanBlock=!state.online&&eligibleBlockers(type,actor.id,targetId).some(p=>p.id===me.id);if(fromBot&&humanCanBlock){state.block={type,targetId,actorId:actor.id,blockerId:me.id,roles,kind:'human-choice'};state.busy=true;render();return}if(!fromBot&&!state.online){const bot=chooseBotBlocker(type,actor.id,targetId,roles);if(bot){state.block={type,targetId,actorId:actor.id,blockerId:bot.id,roles,role:bot.role,kind:'bot-claim'};state.busy=true;state.log.push(`${bot.player.name} bloqueou alegando ser ${bot.role}.`);render();return}}act(type,targetId,fromBot)}
function chooseBotBlocker(type,actorId,targetId,roles){const candidates=eligibleBlockers(type,actorId,targetId).filter(p=>p.bot).map(player=>{const real=player.cards.find(c=>!c.lost&&roles.includes(c.role));const chance=real?.role?(player.cards.filter(c=>!c.lost).length===1?.42:.64):.13;return{player,role:real?.role||roles[Math.floor(Math.random()*roles.length)],chance}}).sort((a,b)=>b.chance-a.chance);return candidates[0]&&Math.random()<candidates[0].chance?candidates[0]:null}
function chooseBotChallenger(role,actorId){const revealed=state.players.flatMap(p=>p.cards).filter(c=>c.lost&&c.role===role).length;const candidates=state.players.filter(p=>p.bot&&p.id!==actorId&&alive(p)).map(bot=>{const held=bot.cards.filter(c=>!c.lost&&c.role===role).length;const evidence=held+revealed;let chance=evidence>=3?1:evidence===2?.68:evidence===1?.22:.1;if(bot.cards.filter(c=>!c.lost).length===1)chance*=.58;chance*=bot.courage||1;return{bot,chance,evidence}}).sort((a,b)=>b.chance-a.chance);const best=candidates[0];return best&&Math.random()<best.chance?best.bot:null}
function resolveBotChallenge(bot,actor,role,type,targetId){state.busy=true;state.log.push(`${bot.name} contestou a alegação de ${actor.name} como ${role}.`);render();setTimeout(()=>{const proof=actor.cards.find(c=>!c.lost&&c.role===role);if(proof){lose(bot);state.log.push(`${actor.name} provou ser ${role}. ${bot.name} perdeu uma influência.`);replaceProvenCard(actor,proof);state.busy=false;render();setTimeout(()=>advanceAction(type,targetId),650)}else{lose(actor);state.log.push(`${actor.name} blefou e perdeu uma influência. A ação falhou.`);state.busy=false;render();setTimeout(next,900)}},850)}
function resolveChallenge(contest){const claim=state.challenge,actor=state.players.find(p=>p.id===claim.actorId),me=state.players.find(p=>p.id===state.myId);state.challenge=null;if(!contest){state.busy=false;advanceAction(claim.type,claim.targetId,true);return}const proof=actor.cards.find(c=>!c.lost&&c.role===claim.role);if(proof){lose(me);state.log.push(`${me.name} contestou, mas ${actor.name} provou ser ${claim.role}. ${me.name} perdeu uma influência.`);replaceProvenCard(actor,proof);state.busy=false;advanceAction(claim.type,claim.targetId,true)}else{lose(actor);state.log.push(`${me.name} contestou ${actor.name}: era um blefe. ${actor.name} perdeu uma influência.`);state.busy=false;render();setTimeout(next,900)}}
function resolveHumanBlock(role){const block=state.block,me=state.players.find(p=>p.id===state.myId);state.block={...block,role};const proof=me.cards.find(c=>!c.lost&&c.role===role);const bot=state.players.filter(p=>p.bot&&p.id!==me.id&&alive(p)).sort(()=>Math.random()-.5)[0];const contest=bot&&Math.random()<(proof?.role?.length ? .4 : .45);state.log.push(`${me.name} bloqueou alegando ser ${role}.`);if(!contest){state.log.push(`O bloqueio de ${me.name} foi aceito.`);state.block=null;state.busy=false;render();setTimeout(next,750);return}state.log.push(`${bot.name} contestou o bloqueio.`);render();setTimeout(()=>{if(proof){lose(bot);replaceProvenCard(me,proof);state.log.push(`${me.name} provou ser ${role}. ${bot.name} perdeu uma influência.`);state.block=null;state.busy=false;render();setTimeout(next,750)}else{lose(me);state.log.push(`${me.name} blefou o bloqueio. A ação continua.`);state.block=null;state.busy=false;render();setTimeout(()=>act(block.type,block.targetId,true),650)}},800)}
function resolveBotBlock(contest){const block=state.block,bot=state.players.find(p=>p.id===block.blockerId),me=state.players.find(p=>p.id===state.myId);if(!contest){state.log.push(`O bloqueio de ${bot.name} foi aceito.`);state.block=null;state.busy=false;render();setTimeout(next,750);return}const proof=bot.cards.find(c=>!c.lost&&c.role===block.role);state.log.push(`${me.name} contestou o bloqueio de ${bot.name}.`);render();setTimeout(()=>{if(proof){lose(me);replaceProvenCard(bot,proof);state.log.push(`${bot.name} provou ser ${block.role}. ${me.name} perdeu uma influência.`);state.block=null;state.busy=false;render();setTimeout(next,750)}else{lose(bot);state.log.push(`${bot.name} blefou o bloqueio. A ação continua.`);state.block=null;state.busy=false;render();setTimeout(()=>act(block.type,block.targetId),650)}},800)}
function botTurn(){const p=state.players[state.turn];if(!alive(p))return next();const targets=state.players.filter(x=>x.id!==p.id&&alive(x));if(p.coins>=10)return requestAction('Golpe',targets[0].id,true);if(p.coins>=7&&Math.random()>.45)return requestAction('Golpe',targets.sort((a,b)=>a.cards.filter(c=>!c.lost).length-b.cards.filter(c=>!c.lost).length)[0].id,true);const options=['Renda','Ajuda externa','Imposto','Roubar','Trocar'];if(p.coins>=3)options.push('Assassinar');const a=options[Math.floor(Math.random()*options.length)];['Roubar','Assassinar'].includes(a)?requestAction(a,targets[Math.floor(Math.random()*targets.length)].id,true):requestAction(a,null,true)}
function render(){const root=$('#app');if(state.screen==='lobby'){root.innerHTML=`<main class="shell"><nav class="topbar"><div class="brand">LA <span>CORTE</span></div><div class="status"><i class="dot"></i> servidor local ativo</div></nav><section class="landing"><div><div class="eyebrow">Um jogo de poder e influência</div><h1>Toda verdade<br>é um <em>risco.</em></h1><p class="lead">Blefe, negocie e elimine seus rivais. Na corte, a confiança é a moeda mais rara.</p><div class="feature-row"><div><b>2–6</b> jogadores</div><div><b>15 min</b> por partida</div><div><b>∞</b> intrigas</div></div></div><div class="glass"><h2>Entre na corte</h2><div class="sub">Escolha como deseja disputar o poder.</div><div class="mode-grid"><button class="mode ${state.mode==='bots'?'active':''}" data-mode="bots"><span class="mode-icon">♞</span><span><strong>Contra bots</strong><small>Partida rápida contra a corte</small></span></button><button class="mode ${state.mode==='create'?'active':''}" data-mode="create"><span class="mode-icon">♜</span><span><strong>Criar sala</strong><small>Abra uma mesa e compartilhe o código</small></span></button><button class="mode ${state.mode==='join'?'active':''}" data-mode="join"><span class="mode-icon">⌁</span><span><strong>Entrar em sala</strong><small>Use o código enviado pelo anfitrião</small></span></button></div><div class="field"><label>Seu nome na corte</label><input id="name" maxlength="18" value="${state.name}" placeholder="Digite seu nome" /></div>${state.mode==='join'?`<div class="field"><label>Código da sala</label><input id="room-code" maxlength="5" value="${state.joinCode||''}" placeholder="ABCDE" autocomplete="off" /></div>`:''}${state.error?`<p class="form-error">${state.error}</p>`:''}<button class="primary" id="enter">${state.mode==='bots'?'Jogar contra bots':state.mode==='create'?'Criar sala privada':'Entrar na sala'} →</button><p class="fine">Nenhum cadastro necessário · Funciona na sua rede local</p></div></section></main>`;bindLobby();return}
 if(state.screen==='room'||state.screen==='waiting_game'){const room=state.room;root.innerHTML=`<main class="shell"><nav class="topbar"><div class="brand">LA <span>CORTE</span></div><button class="ghost" id="leave-room">Sair da sala</button></nav><section class="room-lobby glass"><div class="eyebrow">Sala privada</div><div class="room-code">${room?.code||'•••••'}</div><p class="sub">Compartilhe este link; o código já acompanha o convite.</p><button class="copy-invite" id="copy-invite">${state.shareCopied?'✓ Link copiado':'↗ Copiar link da sala'}</button><div class="room-seats">${(room?.players||[]).map(p=>`<div class="room-seat"><span class="avatar">${p.name[0]}</span><strong>${p.name}</strong>${p.id===room.hostId?'<small>ANFITRIÃO</small>':''}</div>`).join('')}</div>${state.screen==='waiting_game'?'<p class="waiting">Aguardando o anfitrião distribuir as cartas…</p>':state.isHost?`<button class="primary" id="start-room" ${(room?.players.length||0)<2?'disabled':''}>Iniciar partida</button>`:'<p class="waiting">Aguardando o anfitrião iniciar…</p>'}</section></main>`;bindRoom();return}
 root.innerHTML=`<main class="game"><nav class="gamebar"><div class="brand">LA <span>CORTE</span></div><div class="round">Sessão privada · Rodada ${state.round}</div><button class="ghost" id="leave">Sair da mesa</button></nav><section class="board"><div class="opponents">${state.players.filter(p=>p.id!==state.myId).map(playerHTML).join('')}</div><div class="center"><div class="turn-copy">${state.winner?`<div class="winner">${state.winner.name} domina a corte</div>`:`É a vez de<br><b>${state.players[state.turn].name}</b>`}</div>${historyHTML()}${state.winner?'<button class="primary" id="again" style="width:220px;margin-top:24px">Jogar novamente</button>':''}</div></section>${!state.winner?handHTML():''}${state.targetAction?targetModal():''}${state.challenge?challengeModal():''}${state.block?blockModal():''}</main>`;bindGame()}
function historyHTML(){const entries=state.log.slice(-5);return `<section class="chronicle"><header><span>Crônica da corte</span><small>Rodada ${state.round}</small></header><div class="chronicle-list">${entries.map((text,index)=>{const icon=text.includes('roubou')?'◆':text.includes('Duque')||text.includes('alegou')?'♛':text.includes('contestou')?'⚔':text.includes('assassin')?'†':text.includes('reorganizou')?'↻':text.includes('recolheu')||text.includes('ajuda')?'+':'·';const first=text.split(' ')[0];const detail=text.slice(first.length);return `<article class="chronicle-entry ${index===entries.length-1?'latest':''}"><i>${icon}</i><p><strong>${first}</strong>${detail}</p></article>`}).join('')}</div></section>`}
function playerHTML(p){return `<div class="player ${state.players[state.turn].id===p.id?'turn':''} ${!alive(p)?'dead':''}"><div class="avatar">${p.name[0]}</div><strong>${p.name}</strong><div class="coins">◆ ${p.coins} moedas</div><div class="influence">${p.cards.map(c=>c.lost?`<i class="mini-card revealed" style="--mini-portrait:url('${PORTRAITS[c.role]}')"><span>${c.role}</span></i>`:`<i class="mini-card hidden" aria-label="Influência não revelada"><span>?</span></i>`).join('')}</div></div>`}
function handHTML(){const me=state.players.find(p=>p.id===state.myId)||state.players[0],mine=state.players[state.turn].id===me.id&&!state.busy;const must=me.coins>=10;const actions=[['Renda','+1 moeda'],['Ajuda externa','+2 moedas'],['Imposto','Duque · +3'],['Roubar','Capitão · alvo'],['Trocar','Embaixador'],['Assassinar','3 moedas · alvo'],['Golpe','7 moedas · alvo']];return `<footer class="hand"><div class="self-status"><span>Seu tesouro</span><b>◆ ${me.coins}</b><small>moedas</small></div>${me.cards.map(c=>`<div class="role-card ${c.lost?'lost':''}" style="--portrait:url('${PORTRAITS[c.role]}')"><h3>${c.role}</h3><p>${c.lost?'Influência revelada':ROLES[c.role]}</p></div>`).join('')}<div class="actions">${actions.map(([a,d])=>`<button class="action" data-action="${a}" ${!mine||(must&&a!=='Golpe')||(a==='Assassinar'&&me.coins<3)||(a==='Golpe'&&me.coins<7)?'disabled':''}><b>${a}</b><small>${d}</small></button>`).join('')}</div></footer>`}
function targetModal(){const targets=state.players.filter(p=>p.id!==state.turn&&alive(p));return `<div class="modal-wrap"><div class="modal"><div class="eyebrow">Escolha seu rival</div><h2>${state.targetAction}</h2><div class="targets">${targets.map(p=>`<button class="target" data-target="${p.id}"><b>${p.name}</b> · ${p.coins} moedas · ${p.cards.filter(c=>!c.lost).length} influências</button>`).join('')}</div><button class="ghost" id="cancel">Cancelar</button></div></div>`}
function modalContext(){const events=state.log.slice(-3).reverse();const revealed=state.players.flatMap(p=>p.cards.filter(c=>c.lost).map(c=>c.role));return `<aside class="modal-context"><div class="context-title">Contexto da mesa</div><div class="context-revealed"><small>REVELADAS</small><div>${revealed.length?revealed.map(role=>`<span>${role}</span>`).join(''):'<em>Nenhuma influência revelada</em>'}</div></div><div class="context-events">${events.map(text=>`<p>— ${text}</p>`).join('')}</div></aside>`}
function challengeModal(){const c=state.challenge,a=state.players.find(p=>p.id===c.actorId);return `<div class="modal-wrap"><div class="modal modal-with-context"><div class="modal-main"><div class="eyebrow">Alegação de personagem</div><h2>${a.name} diz ser ${c.role}</h2><p class="modal-copy">Se contestar e ele provar a carta, você perde uma influência. Se for blefe, ele perde.</p><div class="response-actions"><button class="danger" id="challenge">Contestar alegação</button><button class="primary" id="allow">Permitir ação</button></div></div>${modalContext()}</div></div>`}
function blockModal(){const b=state.block,actor=state.players.find(p=>p.id===b.actorId),blocker=state.players.find(p=>p.id===b.blockerId);if(b.kind==='human-choice')return `<div class="modal-wrap"><div class="modal modal-with-context"><div class="modal-main"><div class="eyebrow">Ação bloqueável</div><h2>${actor.name} tenta ${b.type.toLowerCase()}</h2><p class="modal-copy">Você pode impedir esta ação alegando uma das influências permitidas. Outros jogadores podem contestar seu bloqueio.</p><div class="block-options">${b.roles.map(role=>`<button class="block-option" data-block-role="${role}"><b>Bloquear com ${role}</b><small>${role==='Duque'?'Impede Ajuda Externa':role==='Condessa'?'Impede Assassinato':'Impede Roubo'}</small></button>`).join('')}</div><button class="ghost" id="allow-block">Permitir ação</button></div>${modalContext()}</div></div>`;return `<div class="modal-wrap"><div class="modal modal-with-context"><div class="modal-main"><div class="eyebrow">Bloqueio declarado</div><h2>${blocker.name} diz ser ${b.role}</h2><p class="modal-copy">${blocker.name} bloqueou ${b.type.toLowerCase()}. Você pode aceitar ou contestar a alegação.</p><div class="response-actions"><button class="danger" id="contest-block">Contestar bloqueio</button><button class="primary" id="accept-block">Aceitar bloqueio</button></div></div>${modalContext()}</div></div>`}
function bindLobby(){$('.fine')?.remove();const enter=$('#enter'),name=$('#name'),roomCode=$('#room-code');const valid=()=>name.value.trim()&&(state.mode!=='join'||roomCode?.value.trim().length===5);enter.disabled=!valid();document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;state.error=null;render()});name.oninput=e=>{state.name=e.target.value;enter.disabled=!valid()};roomCode?.addEventListener('input',e=>{e.target.value=e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,'');state.joinCode=e.target.value;enter.disabled=!valid()});name.onkeydown=e=>{if(e.key==='Enter'&&valid())enter.click()};enter.onclick=()=>{const value=name.value.trim();if(!value||!valid())return;state.name=value;state.joinCode=roomCode?.value.trim().toUpperCase();if(state.mode==='bots')start();else connectRoom(state.mode)}}
function leaveRoom(){state.online=false;state.room=null;state.screen='lobby';roomChannel?.unsubscribe();roomChannel=null;history.replaceState(null,'','/');render()}
function bindRoom(){$('#leave-room').onclick=leaveRoom;$('#start-room')?.addEventListener('click',()=>{const players=state.room.players;start(players);sendRoom('game_started',{players})});$('#copy-invite')?.addEventListener('click',async()=>{const link=`${location.origin}/sala/${state.room.code}`;try{await navigator.clipboard.writeText(link);state.shareCopied=true;render();setTimeout(()=>{state.shareCopied=false;render()},1800)}catch{window.prompt('Copie este convite:',link)}})}
function bindGame(){$('#leave').onclick=leaveRoom;$('#again')?.addEventListener('click',()=>start(state.online?state.room?.players:null));document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>['Roubar','Assassinar','Golpe'].includes(b.dataset.action)?chooseTarget(b.dataset.action):requestAction(b.dataset.action));document.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>{const a=state.targetAction;state.targetAction=null;requestAction(a,b.dataset.target)});$('#cancel')?.addEventListener('click',()=>{state.targetAction=null;render()});$('#challenge')?.addEventListener('click',()=>resolveChallenge(true));$('#allow')?.addEventListener('click',()=>resolveChallenge(false));document.querySelectorAll('[data-block-role]').forEach(b=>b.onclick=()=>resolveHumanBlock(b.dataset.blockRole));$('#allow-block')?.addEventListener('click',()=>{const b=state.block;state.block=null;state.busy=false;act(b.type,b.targetId,true)});$('#contest-block')?.addEventListener('click',()=>resolveBotBlock(true));$('#accept-block')?.addEventListener('click',()=>resolveBotBlock(false))}
render();
